import React, { useContext, useEffect } from 'react';
import Head from 'next/head'
import { UserContext } from '@/UserContext';
import { useRouter } from 'next/router';

export default function Home() {
  const { user, handleLogout } = useContext(UserContext);
  const router = useRouter();
  useEffect(() => {
    if (!user) {
      router.push('/login')
    }
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

      </main>
    </>
  )
}