// login.js

"use client"
import React, { useState, useContext } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { signIn } from 'next-auth/react'
// import { UserContext } from '@/UserContext';
import "../styles/Home.module.css";

function Login() {
  // const [username, setUsername] = useState("");
  // const [password, setPassword] = useState("");
  // const [branchCode, setBranchCode] = useState("");
  // const { user, loginUser } = useContext(UserContext);

  // console.log(user);
    const [username, setUsername] = useState('');
    const [password, setPassword] = useState('');
    const [branchCode, setBranchCode] = useState("");
    // const { user } = useContext(UserContext);
  
    const loginUser = async (event) => {
      event.preventDefault();
  
      try {
        const result = await signIn('credentials', {
          username: username,
            password: password,
            // callbackUrl: "http://localhost:3000/login",
            redirect: false,
        });
  
        if (result.error) {
          console.error('Authentication failed:', result.error);
          alert('Authentication failed');
        } else {
          console.log('User:', user);
          console.log(result)
          router.push("/production-home");
          // You can check result.url and redirect accordingly
        }
      } catch (error) {
        console.error('An error occurred while logging in:', error);
        alert('An error occurred while logging in: ' + error.message);
      }
    };

  return (
    <>
      <Head>
        <title>MSSPL LOGIN PAGE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="h-100 gradient-form">
        <div className="container py-5">
          <div className="row d-flex justify-content-center align-items-center h-100">
            <div className="col-xl-6">
              <div className="card rounded-10 text-black h-100">
                <div className="row g-0 justify-content-center align-items-center">
                  <div className="col-lg-10">
                    <div className="card-body p-md-5 mx-md-4">
                      <div className="text-center pb-2">
                        <Image src="/logo.png" width={115} height={115} alt="logo" />
                        <h6 className="mt-1 mb-5 pb-1 login-head">Multiple Special Steel Pvt. Ltd.</h6>
                      </div>

                      <form onSubmit={(e) => loginUser(e, username, password)}>
                        <p className='login-heading'>Please login to your account</p>

                        <div className="form-floating mb-3">
                          <input
                            type="text"
                            className="form-control"
                            id="floatingInput"
                            placeholder="name@example.com"
                            onChange={(e) => setUsername(e.target.value)}
                            aria-label="Username"
                          />
                          <label htmlFor="floatingInput" className="form-label">User Name</label>
                        </div>

                        <div className="form-floating">
                          <input
                            type="password"
                            className="form-control"
                            id="floatingPassword"
                            placeholder="Password"
                            autoComplete="off"
                            onChange={(e) => setPassword(e.target.value)}
                            aria-label="Password"
                          />
                          <i className="bi bi-eye-slash" id="togglePassword"></i>
                          <label htmlFor="floatingPassword" className="form-label">Password</label>
                        </div>

                        <button
                          className="w-100 btn lg-botton mt-4 mb-4 btn btn-primary"
                          type="submit"
                          aria-label="Log in button"
                        >
                          Log in
                        </button>
                      </form>

                      {branchCode && (
                        <div className="text-center">
                          <p>Branch Code: {branchCode}</p>
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}

export default Login;
